name: Build

on:
  push:
    branches: master
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install node
      uses: actions/setup-node@v3
      with:
       node-version: '16.x'
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install jupyterlab
    - name: Build the extension
      run: |
        jlpm
        jlpm run lint:check
        python -m pip install .

        jupyter labextension list 2>&1 | grep -ie "@jupyterlab-contrib/spellchecker.*OK"
        python -m jupyterlab.browser_check
    - name: Install test dependencies
      run: python -m pip install pytest
    - name: Run python tests
      run: |
        python -m pytest
